
import java.lang.*;

public class JMessageBox extends javax.swing.JFrame {

    /** Creates new form JMessageBox */
    public JMessageBox() {
        initComponents ();
        pack ();
    }

    public JMessageBox(String Texttodisplayed, String BoxTitle) {
        initComponents ();
        jDisplayText.setText(Texttodisplayed);
        setTitle(BoxTitle);
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        jDisplayText = new javax.swing.JTextArea ();
        jOKButton = new javax.swing.JButton ();
        getContentPane ().setLayout (new java.awt.GridBagLayout ());
        java.awt.GridBagConstraints gridBagConstraints1;
        addWindowListener (new java.awt.event.WindowAdapter () {
            public void windowClosing (java.awt.event.WindowEvent evt) {
                exitForm (evt);
            }
        }
        );

        jDisplayText.setDisabledTextColor (new java.awt.Color (204, 204, 204));
        jDisplayText.setBorder (null);
        jDisplayText.setEditable (false);
        jDisplayText.setText ("Text to be displayed");
        jDisplayText.setBackground (new java.awt.Color (204, 204, 204));


        gridBagConstraints1 = new java.awt.GridBagConstraints ();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets (25, 50, 15, 50);
        gridBagConstraints1.weightx = 0.5;
        gridBagConstraints1.weighty = 0.5;
        getContentPane ().add (jDisplayText, gridBagConstraints1);

        jOKButton.setActionCommand ("jOKButton");
        jOKButton.setText ("OK");
        jOKButton.addActionListener (new java.awt.event.ActionListener () {
            public void actionPerformed (java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed (evt);
            }
        }
        );


        gridBagConstraints1 = new java.awt.GridBagConstraints ();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.insets = new java.awt.Insets (0, 0, 10, 0);
        getContentPane ().add (jOKButton, gridBagConstraints1);

    }//GEN-END:initComponents

  private void jOKButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
        this.dispose();
  }//GEN-LAST:event_jOKButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new JMessageBox().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jDisplayText;
    private javax.swing.JButton jOKButton;
    // End of variables declaration//GEN-END:variables

}